export const POKEMON_FETCH = 'POKEMON_FETCH';
export const POKEMON_SUCCESS = 'POKEMON_SUCCESS';
export const POKEMON_ERROR = 'POKEMON_ERROR';

export const POKEMON_DETAIL_FETCH = 'POKEMON_DETAIL_FETCH';
export const POKEMON_DETAIL_SUCCESS = 'POKEMON_DETAIL_SUCCESS';
export const POKEMON_DETAIL_ERROR = 'POKEMON_DETAIL_ERROR';
